### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Xiphe** [mlevison/high-performance-teams-game#10]
I feel like mostly all of the next steps are blocked by us not having an idea how the UI should look like.

I see the following options:

- copy http://ec2-18-223-120-71.us-east-2.compute.amazonaws.com/ and move on from there
- you @mlevison and your team come up with something that I just implement
- I can also suggest a fist step

**Comment by Xiphe** [comment]
As we've discussed, I'll create paper-prototype for how I currently think the UX makes sense.

**Comment by Xiphe** [comment]
Here're the results of the paper prototyping I did:

**Comment by Xiphe** [comment]
whops

**Comment by Xiphe** [comment]
@mlevison I'd like to hear your feedback on the UI proto.

Stuff that comes to my mind:

 - Total User Stories done are currently not visible
 - Final result page is not designed, I'd make it similar to round welcome pages (and show total stories there)
 - As I said maybe add a "outro" page where the user stories are "rolled" (Maybe even make that interactive / animated to give users more of a "I did this user story" feeling.)

**Comment by mlevison** [comment]
There is a lot here, I will do my best to address each element in order:
- Top level tabs to jump between game and rules - Excellent.
- 2 Screens per round - welcome message and then actions list. _The challenge is that they may need to review the welcome message after the fact_

*Actions*
- All available actions are displayed as Icon/Image in one Column - _If understand correctly each action has a cell in a row? - Not what I had imagined - open to trying._
- Single Click on Action overlays the calc column with action details _It's this part that I'm unsure how it will work, however lets try and see_
- Double-click/tab on Action directly selects/unselects it - _Ok. Alternative option - selection is checkbox_
- new actions are displayed in new row - _yes_
- rows can be collapsed (may auto-collapse for old rounds?) - _How about coalesce previous rows into 1? _
- actions that can not be selected due to dependency are grayed-out but visible - _excellent idea_
- dependencies are either visible or stated in action description - _How would we make visible?_
- Highlights - _3 suggestions all seem good_

*Calculations*
Other Column shows current calculation (Start Cap + effects + action costs + user stories) - _Confusing if you mean column or row. Suggest try something and I will react._

- Next round button is always clickable but will become highlighted when at least two actions are selected or no more action can be afforded - _Maybe it should just always be clickable, no need to highlight. I want people to experiment with bad choices_
- _Gremlins take effect at the of round N and therefore their effect should be displayed in round n+1. However they've already reduced the capacity by then_ 
- User Stories - _Too make it feel more like real life if they spend more 30% of their capacity on user stories - highlight the user Stories yellow. More than 50% use a red highlight. If its easy I would even add a text warning from their manager in either case saying - "not enough time spent on feature work"_
- Small screens - _For now this is targeted at puter/tablet users - small screens can be handled once we have the basics down_

Missing
- No cumulative log of the actions taken, by round and also the gremlins that happened

**Comment by Xiphe** [comment]
- I seemed to have mixed up columns and rows, sorry.

- H: 2 Screens per round - welcome message and then actions list. 
  M: _The challenge is that they may need to review the welcome message after the fact_
  H: There will be a "show description button"

- H: rows can be collapsed (may auto-collapse for old rounds?)
   M: _How about coalesce previous rows into 1?_
   H: Open to trying

- H: dependencies are either visible or stated in action description
   M: _How would we make visible?_
   H: By drawing a dependency-line. See left action in both columns here (might be complicated to calculate this, though):
   ![image](https://user-images.githubusercontent.com/911218/98523116-d2516600-2275-11eb-872f-ae07b881a244.png) 

- H: Next round button is always clickable but will become highlighted when at least two actions are selected or no more action can be afforded
   M: _Maybe it should just always be clickable, no need to highlight. I want people to experiment with bad choices_
   H: Ok :+1:. my thought was that maybe the button is too small and will be overseen but thats premature optimisation.
   
- M: _Gremlins take effect at the of round N and therefore their effect should be displayed in round n+1. However they've already reduced the capacity by then_
   H: I don't understand what I'm supposed to do with this statement. I think I've implemented it this way.

- M: _User Stories - Too make it feel more like real life if they spend more 30% of their capacity on user stories - highlight the user Stories yellow. More than 50% use a red highlight. If its easy I would even add a text warning from their manager in either case saying - "not enough time spent on feature work"_
   H: You prob. mean if they spend 30% on NON-user stories then yellow highlight, and red highlight when less then 50% on user stories, right? This way it makes sense to me and I like the idea a lot :)

- H: Small screens
   M: _For now this is targeted at puter/tablet users - small screens can be handled once we have the basics down_
   H: I'ts a magnitude more easy to implement a responsive layout on a greenfield then trying to tweak a non-responsive layout later on. + Hopefully people will just try out the game to get an idea (maybe on their phone) before they're starting to play it with their team

- M: _No cumulative log of the actions taken, by round and also the gremlins that happened_
  H: Good point. I hope that the skill-tree view of icons gives the payers a good idea of what happened in the past.
  But Additionally I'd suggest to show the "current calculation" rows of all rounds on the results screen.

**Comment by mlevison** [comment]
All comments above match my understanding. One clarification:

> M: Gremlins take effect at the of round N and therefore their effect should be displayed in round n+1. However they've already reduced the capacity by then
> H: I don't understand what I'm supposed to do with this statement. I think I've implemented it this way

M: Framed differently the user makes their choices; hits finish round. Only then is gremlin discovered.

**Comment by Xiphe** [comment]
Closing since it seems to me as if everything that's not already implemented now has its own repo.
