### ISSUE TITLE
When the number of completed stories exceeds 40...

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#110]
....they don't get displayed correctly on the graph:
![Graph Too Small](https://i.imgur.com/52yHeUM.png)
...
The challenge when we have 300+ complete stories how to visualize?

- A three y axis chart: https://plotly.github.io/excel/three-y-axes/
- Two separate charts?
- Just allow the overall scale to be really tall

**Comment by Xiphe** [comment]
I'd say leave as is.

The chart shows complete stories per round. In the screenshot above, 303 stories have been completed in total. I don't see a reason why we would want that number on the chart

**Comment by Xiphe** [comment]
We could add "in total" to not cause confusion

**Comment by mlevison** [comment]
I added "this round" in the legend. I think better would be a title. Challenge is that I can't find how you give a chart a title.

**Comment by Xiphe** [comment]
not sure what you mean

**Comment by mlevison** [comment]
I'm saying that a title above the graph would make it easier to provide context. 
--
The original issue/bug came about because I associated the chart with the totals above. 
--
Looking at the rechart docs, I can't find a way to give charts a title.

**Comment by Xiphe** [comment]
You can add a headline above the chart itself

**Comment by mlevison** [comment]
I understood the html - I have no idea where to add it. React takes normal html that I understand and hides it.

**Comment by Xiphe** [comment]
In fact, react does not take "normal" html...

Shot react/JSX excursion:

1. All html-style syntax in javascript/typescript files is not valid javascript and is compiled to a function call before being executed by a browser/node
   ```jsx
   import React from 'react';
   const headline = <h1 className="test">Hello</h1>
   // is compiled to
   const headline = React.createElement('h1', { className: 'test' }, 'Hello')
   ```
   
   It's syntactic sugar so that we do not have to type `React.createElement` all the time.  
   Thats also the reason we have to `import React from 'react';` in most files, because otherwise it would be `undefined`.  
   Typescript does the compiling because we configured it to ["jsx": "react"](https://github.com/mlevison/high-performance-teams-game/blob/main/tsconfig.json#L16). Theoretically we could configure it to compile to something else like `const headline = myCreateElementAlternative('h1', { className: 'test' }, 'Hello')`
2. `React.createElement('h1', /* ... */)` is a declarative way of writing
    ```js
    const headline = document.createElement('h1');
    headline.className = 'test';
    headline.innerText = 'Hello';
    
    someParentElement.appendChild(headline);
    ```

    Where react is taking care of doing as little interactions with the [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) as possible (and giving us a declarative way to manage state and interactions)

**Comment by Xiphe** [comment]
Coming back to the headline: 

I assume you want to change [`src/app/components/Round/Results.tsx#L175`](https://github.com/mlevison/high-performance-teams-game/blob/main/src/app/components/Round/Results.tsx#L175) this way

```diff
           </Button>
         ) : null}
       </div>
+      <h3>My Headline</h3>
       <CapStoryChart
         rounds={[
           ...props.pastRounds,
```

I found the location by searching for "Roll for User Stories" in the codebase. Alternatively you could use the dev-tools of your browser to identify components in the area you want to change. There are also the [react-developer-tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) but I personally rarely use them.

**Comment by mlevison** [comment]
Fixed
