### ISSUE TITLE
Communication Drag

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#29]
Implement Communication Drag

**Comment by Xiphe** [comment]
Just to make sure. Since you've self-assigned this it's a "note to self" right?

**Comment by mlevison** [comment]
yes

**Comment by mlevison** [comment]
Not sure how to reference a checkin in an issue :-) and I know it could have been a pull request.

My problem comes in not knowing how to mock out only a specific function. 

In the round 1.spec file I find:
`/* disable game effect to only tests single actions */
jest.mock('../gameEffects', () => ({
  gameEffects: [],
}));`

From this I understand to mock out the game effects I just replace the array. So far so good. 
The challenge is two fold:
- how to construct the mock so we only disable one function? *The mock in the above example just eliminates all effects*
- how to construct the mock so it only affects one test/describe block? *I guess I handle that by putting the specific item inside the describe function.*

Other open questions
- Why is it necessary to use a fake/mock action to test that the drag effect is halted. Why not use a real action?

**Comment by Xiphe** [comment]
> My problem comes in not knowing how to mock out only a specific function. 

There are multiple ways to do this (see [jest docs on mock-functions](https://jestjs.io/docs/en/mock-functions)). If you tell me which function you want to mock I can give you more specific advise. 
 
> how to construct the mock so we only disable one function

```ts
jest.mock('../gameEffects', () => {
  const original = jest.requireActual('../gameEffects').gameEffects;
  return {
    gameEffects: [original[1]],
  };
});
```

> how to construct the mock so it only affects one test/describe block

For module level mocks there is [`jest.doMock`](https://jestjs.io/docs/en/jest-object#jestdomockmodulename-factory-options) but it does not work that easily because imports are only done once per file so if you first import from a module then mock it and import again (all in same file) then the cached value from first import will be used. Constructing an application to work around this will cause  complexity only for testing.

Often it's easier to just use two spec files with different mocks or use [`jest.spyOn`](https://jestjs.io/docs/en/jest-object#jestspyonobject-methodname) but in the case of the effects, it does not work on the array.

The last resort would be to directly manipulate effect array manually

```
import { gameEffects } from '../gameEffects';

const originalEffects = [...gameEffects];

afterEach(() => {
  gameEffects.length = 0;
  gameEffects.push(...originalEffects);
})

it('tests only one effect', () => {
  gameEffects.length = 0;
  gameEffects.push(originalEffects[0]);

  /* ... some test */
});
```

**Comment by mlevison** [comment]
Your fix took care of this. Thanks.
