### ISSUE TITLE
effect description could be calculated from action Name.

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#30]
https://github.com/mlevison/high-performance-teams-game/blob/8fb5abdce8e9b22b522f219cee9553a2e23743b9/src/state/gameActions/gameActions.ts#L39-L39

**Comment by mlevison** [comment]
As an example: 

WORKING_AGREEMENTS: {
    name: 'Working Agreements',
    available: { round: 1 },
    description: 'Create Team Working Agreements',
    cost: 1,
    effect: () => ({ capacity: 1, title: 'TODO: #30 Working Agreements active' }),
  },

So instead of calling effect.title. Why action.name + "Active"

**Comment by Xiphe** [comment]
I'd assume that this leads to a pretty static/technical list of effects. I mean as a player I know that it's "active" because I can see it in the effects list. 

My thought here was to have something like
ActionName: "Working Agreements"
Effect: "Higher efficiency due to less micro arrangements"

--
I'll create a PR that shows how to re-use the "name" in the effect method and then you can decide if you adept it to the other actions ok?

**Comment by mlevison** [comment]
Your point is good. I will leave this alone for the moment and try writing some effects descriptions.
