### ISSUE TITLE
Results Log

### ISSUE THREAD

**Issue by mlevison** [mlevison/high-performance-teams-game#81]
We need a results log at game end and preferably each round. It should display the action name, description (?), more info link and the round selected. The same applies for Gremlins.

The goal is to players see how they got the point they did. It will also help for retrying or improving the strategy for future rounds. Finally it will help players take away a list of links (via more info) that will inspire them to greater improvement.

---

## User stories

- [ ] 1.  As a game maintainer I want the log to be useful for debugging.
   Given I receive a bug/feature request from a user
   Then I want to be able to ask the user for the log of the game
   And I want to be able to re-create the game/state by following the log
- [ ] 2. As a player I want the log to be useful to reflect on how I got here
   Given I am in round 5 
   Then I want to be able to see which actions I've taken in round 1
- [ ] 3. As a player I want the log to be useful to improve my strategy for future 
   Given I finished the game
   And I read the log
   Then I want to be able to make sense of all the steps i've done 
- [ ] 4. As a player I want to use the log to compare the results
  Given I finished multiple games
  Then I want to have some way of comparing the results of these
- [ ] 5. As a team I want the log to help in discussions about the results 
  Given I finished the game
  Then I want some way of referring to its details without needing to keep the game page open
- [ ] 6. As a player I want to be able to save the log
  Given I finished the game
  Then I want some way of persisting its outcome  (Any HTML page can be copy+pasted into a doc.)
- [ ] 7. As @mlevison I want readers of a saved log to be referred to APR website
  Given a player finished the game and reads the log
  Then I want "more" links to be placed in the log 
  And intrigued players would use them to learn more

**Comment by Xiphe** [comment]
I don't understand how this is different from the review feature.

In each round they can see the actions selected in previous rounds + the ones of this. Active gremlins are visible.

+ when Reviewing they can jump between rounds to see what happened there + descriptions etc.

---

I'll quickly try to blindly implement what you're saying and see if it clicks or you can give me feedback on that.

**Comment by mlevison** [comment]
...differences:
- at the end of the game its nice to be reminded of the decisions made in the past
- they might play several rounds of the game and want to compare the results
- they might want to discuss the results with their team or me afterwards 
....

**Comment by Xiphe** [comment]
> at the end of the game its nice to be reminded of the decisions made in the past

How does the review feature not cover this?

> they might play several rounds of the game and want to compare the results
> they might want to discuss the results with their team or me afterwards

How would I compare the results using the log? Does it have a stable link that I can open even after starting the game? Can I print it?

**Comment by mlevison** [comment]
>>   at the end of the game its nice to be reminded of the decisions made in the past
> How does the review feature not cover this?

Per round it does. However - after 10 rounds of play the user is unlikely to remember the decisions taken. Consider also in a workshop I will want people to discuss their results and the tradeoffs in getting there. For that they need a list of the actions they took.

Results can be saved by copying and pasting to document. Also the browser print function. etc. 

No stable link. Nothing fancy.

**Comment by Xiphe** [comment]
I'm not sure if we're talking about the same "review" feature. Maybe you have't found it yet? 

When being on the results page, click the "Review Game" Button.

<img width="502" alt="Screenshot 2020-12-14 at 18 20 29" src="https://user-images.githubusercontent.com/911218/102113350-39e06f80-3e39-11eb-936c-545e3ff0aef1.png">

**Comment by mlevison** [comment]
Ah I hadn't seen that. I didn't intend that feature. I really just wanted a text log of all the actions, gremlins by round.

Along with all the other reasons listed. If someone gets to an unexpected state, I could use the log to write a test case and see how they got there.

**Comment by Xiphe** [comment]
> Ah I hadn't seen that. I didn't intend that feature. I really just wanted a text log of all the actions, gremlins by round.

As I've stated in https://github.com/mlevison/high-performance-teams-game/pull/74 it was quite simple to implement and didn't required any additional UI creation & thought on how to display stuff. And from my understanding back then it well serves the purpose of letting the team review their actions per round.

 > I could use the log to write a test case and see how they got there.

This is yet another specification to the log I was not aware of. In order to be most useful for debugging then it would make sense that the order of actions taken is also captured (which is currently not port of the game state).

**Comment by Xiphe** [comment]
@mlevison To help me further wrap my head around the log I've tried to sum up [everything we've discussed in user stories](https://github.com/mlevison/high-performance-teams-game/issues/81#issue-762681710)

Honestly: It seems to me as if you're trying to fit to much into the feature.
But i'm going to try my very best.

Besides that: It would be quite simple to display a link on the result page that players could save and share. 
When I open such a link then I would see the results page of the game where the link was created and I could also use the review feature.

With that in mind I'll add a log that focuses on debugging and printing because these are not covered by the review. And then we see where we go from there.
